'use client';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Navbar from './components/layout/Navbar/page';
import { usePathname } from 'next/navigation';
import { SessionProvider } from 'next-auth/react';
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
const poppins = Poppins({ subsets: ['latin'], weight: ['500'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const nodata = ['/login', '/register'];
  return (
    <html lang="en">
      <body className={`${poppins.className}  scroll-smooth overflow-x-hidden`}>
        <SessionProvider>
          {!nodata.includes(pathname) && <Navbar />}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
